apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-nodejs-app-v44-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hoangphuc841/advanced-nodejs-app-v44-gitops
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: advanced-nodejs-app-v44
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
